coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 80%
        base: auto 
        paths: 
          - "src"
       # advanced settings
        if_ci_failed: error
        only_pulls: true