name: coverage

on: 
  push:
    branches:
      - main

jobs:
  test-with-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install       
      - name: testing with coverage
        run: npm run coverage
      - name: push coverage report
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: coverage
          FOLDER: coverage
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Coverage: ({sha}) {msg}"